<a href="https://colab.research.google.com/github/glisserok/grigoriyvolkov/blob/main/Lab_1_KSVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

vector_1 = np.arange(1, 21)
print("Завдання 1:", vector_1)

matrix_ones = np.ones((4, 4))
print("\nЗавдання 2:\n", matrix_ones)

matrix_rand_neg = np.random.uniform(-1, 1, (5, 5))
print("\nЗавдання 3:\n", matrix_rand_neg)

matrix_rand_pos = np.random.rand(3, 3)
print("\nЗавдання 4:\n", matrix_rand_pos)

vec_a = np.random.randint(1, 21, 6)
vec_b = np.random.randint(1, 21, 6)
print("\nЗавдання 5:")
print("Масив A:", vec_a)
print("Масив B:", vec_b)
print("Додавання:", vec_a + vec_b)
print("Віднімання:", vec_a - vec_b)
print("Множення:", vec_a * vec_b)

mat_a = np.random.randint(1, 6, (3, 2))
mat_b = np.random.randint(1, 6, (2, 4))
res_mult = np.dot(mat_a, mat_b)
print("\nЗавдання 6:\n", res_mult)

mat_to_transp = np.random.rand(3, 3)
print("\nЗавдання 7 (Оригінал):\n", mat_to_transp)
print("Транспонована:\n", mat_to_transp.T)

mat_diff1 = np.random.randint(1, 11, (3, 3))
mat_diff2 = np.random.randint(1, 11, (3, 3))
print("\nЗавдання 8 (Різниця):\n", mat_diff1 - mat_diff2)

mat_prod1 = np.random.randint(-5, 6, (3, 3))
mat_prod2 = np.random.randint(-5, 6, (3, 3))
print("\nЗавдання 9 (Добуток):\n", np.dot(mat_prod1, mat_prod2))

mat_sum = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(mat_sum, axis=1).reshape(-1, 1)
print("\nЗавдання 10 (Матриця):\n", mat_sum)
print("Вектор-стовпчик сум:\n", row_sums)

Завдання 1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Завдання 2:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Завдання 3:
 [[-0.9989942  -0.26644344  0.99065018 -0.26437138 -0.98749616]
 [ 0.48610421  0.10324295  0.72131442 -0.37657271 -0.69617078]
 [-0.30606745 -0.14784649  0.04013444 -0.62747997  0.64546665]
 [-0.87496825  0.63979348  0.74418664 -0.45419561  0.40803871]
 [-0.61511447  0.48391051 -0.91281017 -0.25754279 -0.44627398]]

Завдання 4:
 [[0.34859024 0.97679234 0.5535636 ]
 [0.48299533 0.73794241 0.97500265]
 [0.67617177 0.07125051 0.52789248]]

Завдання 5:
Масив A: [18 12  4  3  1 15]
Масив B: [20 13 18 16  9  6]
Додавання: [38 25 22 19 10 21]
Віднімання: [ -2  -1 -14 -13  -8   9]
Множення: [360 156  72  48   9  90]

Завдання 6:
 [[30 28 40  8]
 [37 25 45  9]
 [32 24 40  8]]

Завдання 7 (Оригінал):
 [[0.90426283 0.76598824 0.99519978]
 [0.42074893 0.35477698 0.9607803 ]
 [0.78875203 0.65533265 0.42107741]]
Транспонована:
 [[0.90426283